def raise_exception_msg(message=""):
    try:
        return(value)
    except NameError:
        print(message)
